#!/bin/bash

br="br0"
tap="qemu_tap_0"
inet=enp3s0

while [ "$#" -gt 0 ]; do
  case "$1" in
		--iface)
  		if [ -z "$2" ]; then
  			echo "--iface required args"
  			exit 1
  		fi
  		inet="$2"
  		shift 2
			;;
  	--tap)
  		if [ -z "$2" ]; then
  			echo "--tap required args"
  			exit 1
  		fi
  		tap="$2"
  		shift 2
  		;;
    *)
      echo "Usage: $(basename $0) { --iface wlp2s0b1 | --tap }"
      exit 1
      ;;
  esac
done

modprobe -v tun || exit $?
modprobe -v kvm-intel || exit $?

gateway=$(networkctl status $inet | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n1)

tee /etc/systemd/network/10-${br}.netdev << EOF
[NetDev]
Name=$br
Kind=bridge
EOF

tee /etc/systemd/network/20-${br}.network << EOF
[Match]
Name=$br

[Network]
Address=$gateway/24
DHCPServer=yes
IPForward=yes

[DHCPServer]
DNS=8.8.8.8
DNS=8.8.4.4
EOF

tee /etc/systemd/network/40-${tap}.netdev << EOF
[NetDev]
Name=$tap
Kind=tap
Mode=bridge
Owner=kvm
EOF

tee /etc/systemd/network/50-${tap}.network << EOF
[Match]
Name=$tap

[Network]
Bridge=$br
EOF

_packages=(
	"qemu-system-x86"
	"qemu-system-gui "
	"swtpm" # TMP
	"ovmf" # BIOS SECUREBOOT
	"iptables"
)

apt install --no-install-suggests --no-install-recommends  ${_packages[@]} || exit $?

iptables -t nat -D POSTROUTING -s ${gateway%.*}.0/24 -o $inet -j MASQUERADE
echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A POSTROUTING -s $gateway/24 -o $inet -j MASQUERADE
# iptables -t nat -L POSTROUTING -n --line-numbers ### CEK
# iptables -t nat -D POSTROUTING 1 ### DELETE

systemctl restart systemd-networkd || exit $?